version: "3.8"
services:
  postgres:
    image: 'postgres'
    volumes: 
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - ./graphQL/prisma/.env

  graphql:
    build: ./graphQL
    ports:
      - '4000:4000'
    volumes:
      - /graphQL/node_modules
      - ./graphQL/src:/graphQL/src
      - ./graphQL/prisma:/graphQL/prisma
    stdin_open: true
    tty: true
    depends_on: 
      - postgres

  backend:
    build: ./
    ports:
      - '8080:8080'
    volumes: 
      - /app/node_modules
    env_file: 
      - ./.env
    depends_on:
      - postgres

  client:
    build: ./client
    ports: 
      - '5050:5050'
    volumes: 
      - ./client/src:/client/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  pgdata: